cache: &node_modules
  policy: pull
  paths: [node_modules/]
  key:
    files: [yarn.lock]

default:
  image: node:16.18.0
  tags: [k8s]

stages:
  - setup
  - typecheck
  - code quality
  - test

##

setup:
  stage: setup
  needs: []
  except: [tags]

  # allow writing to cache
  cache:
    <<: *node_modules
    policy: pull-push

  script: [yarn --frozen-lockfile]

##

typecheck:
  stage: typecheck
  needs: [setup]
  except: [tags]

  script: [yarn typecheck]
##

eslint:
  stage: code quality
  needs: [typecheck]
  except: [tags]

  script: [yarn lint]

prettier:
  stage: code quality
  needs: [typecheck]
  except: [tags]

  script: [yarn format]

##

jest:
  stage: test
  needs: [typecheck]
  except: [tags]

  script: [yarn test:cov]